name: Build Husky Plus Firmware

# Controls when the workflow will run
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'
  # Triggers the workflow on push or pull request events but only for the develop branch


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fwbuild:
    # The type of runner that the job will run on
    name: Build all firmware to make sure everything works
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install compilers
        run: >- 
          sudo apt install -y make build-essential gcc-arm-none-eabi
      - name: Build plus capture firmware
        run: |
          cd ChipWhisperer-Husky/src/
          git submodule update --init naeusb
          make TARGET=ChipWhisperer-Husky-Plus -j
      - name: Upload binaries and versions
        uses: actions/upload-artifact@v4
        with:
          name: Husky Plus binary
          path: |
            ChipWhisperer-Husky/src/ChipWhisperer-Husky.bin
            ChipWhisperer-Husky/src/version.txt